name: C/C++ CI

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: apt-get update && apt-get install -y mingw-w64 zip
      - name: make
        run: make
      - name: Generate release
        run: |
          cd release
          zip -r ${GITHUB_REF}_linux.zip linux/*
          zip -r ${GITHUB_REF}_win64.zip win64/*
      - name: Upload the release
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: 'release/*.zip'
