name: C/C++ CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 zip
      - name: make
        run: make
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate release
        run: |
          cd release
          zip -r ${{ env.RELEASE_VERSION }}_linux.zip linux/*
          zip -r ${{ env.RELEASE_VERSION }}_win64.zip win64/*
      - name: Upload the release
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: 'release/*.zip'
